import Foundation

struct ConversationNamer {
    /// Generate a title in MMdd-N format based on date and existing conversations.
    /// N is the 1-based count of conversations on that calendar day (across all projects).
    static func title(for date: Date, existingTitles: [String]) -> String {
        let mmdd = DateFormatter.mmdd.string(from: date)
        let sameDayCount = existingTitles.filter { $0.hasPrefix(mmdd + "-") }.count
        return "\(mmdd)-\(sameDayCount + 1)"
    }

    /// Check if a title is in the auto-generated MMdd-N format.
    static func isAutoGenerated(_ title: String) -> Bool {
        return title.range(of: "^\\d{4}-\\d+$", options: .regularExpression) != nil
    }
}

extension DateFormatter {
    static let mmdd: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "MMdd"
        return f
    }()
}
